[package]
name = "decimal"
version = "0.3.3"
edition = "2021"

[features]
serde = ["serde_crate", "serde_json"]

[dependencies]
anchor-lang = "0.24.2"
serde_json = { version = "1.0", optional = true }
uint = "0.9"

[dependencies.serde_crate]
package = "serde"
version = "1.0"
optional = true
